name: spaceflightobserver
favicon: null
layout_spectrum: 0.24777413392439485
typography_spectrum: 0.34534954698756337
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.49272348871454597
  lightness: 0.8646870490629226
  saturation: 0.4071591319516301
  rhythmicContrast: 0.15723137045279145
purpose: []
